### ISSUE TITLE
Post OpenAI GPT-4 Turbo 'openai' has no attribute 'api_base'

### ISSUE THREAD

**Issue by nickknyc** [graphsignal/graphsignal-python#2]
I am using the new OpenAI GPT-4-1106-preview

I am now getting this error when I run. Still seems to log stuff, but something is probably wrong :^(

```
AttributeError: module 'openai' has no attribute 'api_base'
Failed to initialize recorder for module: openai
Traceback (most recent call last):
  File "d:\Studio13\S13ManagedFab\S13bot\.venv\Lib\site-packages\graphsignal\tracer.py", line 249, in initialize_recorders_for_module
    recorder.setup()
  File "d:\Studio13\S13ManagedFab\S13bot\.venv\Lib\site-packages\graphsignal\recorders\openai_recorder.py", line 54, in setup
    self._api_base = openai.api_base
                     ^^^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'api_base'
```

**Comment by jgabriellima** [comment]
Yes, I went through the same situation. the lib is out of date with the new version of OpenAI python SDK > 1.0

```
You tried to access openai.Completion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
```
